"""
ⒸAngelaMos | 2025
constants.py
"""

EMAIL_MAX_LENGTH = 320
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128
PASSWORD_HASH_MAX_LENGTH = 1024
FULL_NAME_MAX_LENGTH = 255

TOKEN_HASH_LENGTH = 64
DEVICE_ID_MAX_LENGTH = 255
DEVICE_NAME_MAX_LENGTH = 100
IP_ADDRESS_MAX_LENGTH = 45

API_VERSION = "v1"
API_PREFIX = f"/{API_VERSION}"

TOPIC_MAX_LENGTH = 200
HASHTAG_MAX_COUNT = 5
HOOK_TEXT_MAX_LENGTH = 500
SCRIPT_MAX_LENGTH = 10000
TITLE_MAX_LENGTH = 300
URL_MAX_LENGTH = 2048
TAG_MAX_LENGTH = 50

LINKEDIN_POST_MAX_LENGTH = 3000
LINKEDIN_VISIBLE_CHARS = 220
TWITTER_TWEET_MAX_LENGTH = 280
TWITTER_THREAD_MAX_TWEETS = 25
REDDIT_TITLE_MAX_LENGTH = 300
REDDIT_POST_MAX_LENGTH = 40000

DEFAULT_ENGAGEMENT_RATE_THRESHOLD = 0.05
HIGH_ENGAGEMENT_RATE_THRESHOLD = 0.10
VIRAL_ENGAGEMENT_RATE_THRESHOLD = 0.20

MIN_HOOK_USES_FOR_STATS = 3
HOOK_PERFORMANCE_DECAY_DAYS = 90

MAX_HOOK_VARIATIONS = 20
MAX_SENTENCE_VARIATIONS = 10
MAX_CTA_VARIATIONS = 3
MAX_IDEAS_GENERATED = 10
