"""add_identity_tables

Revision ID: aa1123bcf1ae
Revises: 9a0f191ed4f7
Create Date: 2025-12-15 07:30:40.944399
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aa1123bcf1ae'
down_revision: Union[str, None] = '0ab6220c405b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum types before using them in columns (IF NOT EXISTS for idempotency)
    op.execute("DO $$ BEGIN CREATE TYPE preferencetype AS ENUM ('engagement_winner', 'personal_enjoyment', 'burnt_out_on', 'wants_to_make'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE platformtype AS ENUM ('tiktok', 'youtube', 'instagram', 'reddit', 'linkedin', 'twitter'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE engagementlevel AS ENUM ('low', 'medium', 'high', 'viral'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE passionlevel AS ENUM ('interested', 'passionate', 'obsessed'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE proficiencylevel AS ENUM ('beginner', 'intermediate', 'advanced', 'expert'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE strengthsource AS ENUM ('self_identified', 'others_tell_him'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    # Identity tables modifications only - content studio table operations removed
    op.add_column('content_preferences', sa.Column('preference_type', sa.Enum('engagement_winner', 'personal_enjoyment', 'burnt_out_on', 'wants_to_make', name='preferencetype'), nullable=False))
    op.add_column('content_preferences', sa.Column('platform', sa.Enum('tiktok', 'youtube', 'instagram', 'reddit', 'linkedin', 'twitter', name='platformtype'), nullable=True))
    op.add_column('content_preferences', sa.Column('engagement_level', sa.Enum('low', 'medium', 'high', 'viral', name='engagementlevel'), nullable=True))
    op.create_index('idx_content_prefs_platform', 'content_preferences', ['platform'], unique=False)
    op.create_index('idx_content_prefs_type', 'content_preferences', ['preference_type'], unique=False)
    op.add_column('identity_interests', sa.Column('passion_level', sa.Enum('interested', 'passionate', 'obsessed', name='passionlevel'), nullable=False))
    op.create_index('idx_interests_passion', 'identity_interests', ['passion_level'], unique=False)
    op.add_column('identity_skills', sa.Column('proficiency', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='proficiencylevel'), nullable=False))
    op.create_index('idx_skills_proficiency', 'identity_skills', ['proficiency'], unique=False)
    op.add_column('identity_strengths', sa.Column('source', sa.Enum('self_identified', 'others_tell_him', name='strengthsource'), nullable=False))
    op.create_index('idx_strengths_source', 'identity_strengths', ['source'], unique=False)
    op.add_column('platform_goals', sa.Column('platform', sa.Enum('tiktok', 'youtube', 'instagram', 'reddit', 'linkedin', 'twitter', name='platformtype'), nullable=False))
    op.create_index('idx_platform_goals_platform', 'platform_goals', ['platform'], unique=False)
    op.create_unique_constraint('uq_identity_platform', 'platform_goals', ['identity_id', 'platform'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_identity_platform', 'platform_goals', type_='unique')
    op.drop_index('idx_platform_goals_platform', table_name='platform_goals')
    op.drop_column('platform_goals', 'platform')
    op.drop_index('idx_strengths_source', table_name='identity_strengths')
    op.drop_column('identity_strengths', 'source')
    op.drop_index('idx_skills_proficiency', table_name='identity_skills')
    op.drop_column('identity_skills', 'proficiency')
    op.drop_index('idx_interests_passion', table_name='identity_interests')
    op.drop_column('identity_interests', 'passion_level')
    # Identity tables modifications only - content studio table operations removed
    op.drop_index('idx_content_prefs_type', table_name='content_preferences')
    op.drop_index('idx_content_prefs_platform', table_name='content_preferences')
    op.drop_column('content_preferences', 'engagement_level')
    op.drop_column('content_preferences', 'platform')
    op.drop_column('content_preferences', 'preference_type')

    # Drop enum types after all columns using them are dropped
    op.execute("DROP TYPE IF EXISTS preferencetype CASCADE")
    op.execute("DROP TYPE IF EXISTS platformtype CASCADE")
    op.execute("DROP TYPE IF EXISTS engagementlevel CASCADE")
    op.execute("DROP TYPE IF EXISTS passionlevel CASCADE")
    op.execute("DROP TYPE IF EXISTS proficiencylevel CASCADE")
    op.execute("DROP TYPE IF EXISTS strengthsource CASCADE")
    # ### end Alembic commands ###
