"""add job_applications table

Revision ID: 1348b14f44a4
Revises: 20251231_planner
Create Date: 2026-01-03 10:13:51.566545
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1348b14f44a4'
down_revision: Union[str, None] = '20251231_planner'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('identity_name', sa.String(length=200), nullable=False),
    sa.Column('position_title', sa.String(length=200), nullable=False),
    sa.Column('job_url', sa.String(length=2048), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('offer_amount', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('remote_type', sa.Enum('unknown', 'onsite', 'hybrid', 'remote', name='remotetype'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=150), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('application_status', sa.Enum('unknown', 'saved', 'applied', 'withdrawn', name='applicationstatus'), nullable=False),
    sa.Column('interview_rounds', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Enum('unknown', 'pending', 'rejected', 'offer', 'ghosted', 'accepted', 'declined', name='outcome'), nullable=False),
    sa.Column('job_type', sa.Enum('unknown', 'full_time', 'part_time', 'contract', 'internship', 'freelance', name='jobtype'), nullable=False),
    sa.Column('experience_level', sa.Enum('unknown', 'entry', 'mid', 'senior', 'lead', 'principal', 'executive', name='experiencelevel'), nullable=False),
    sa.Column('priority', sa.Enum('unknown', 'low', 'medium', 'high', 'dream', name='priority'), nullable=False),
    sa.Column('date_saved', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_applied', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_first_response', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_outcome', sa.DateTime(timezone=True), nullable=True),
    sa.Column('followup_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_job_applications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_applications'))
    )
    op.create_index('idx_job_app_date_applied', 'job_applications', ['date_applied'], unique=False)
    op.create_index('idx_job_app_outcome', 'job_applications', ['outcome'], unique=False)
    op.create_index('idx_job_app_status', 'job_applications', ['application_status'], unique=False)
    op.create_index('idx_job_app_user', 'job_applications', ['user_id'], unique=False)
    op.drop_index(op.f('idx_challenge_start'), table_name='challenges')
    op.create_index('idx_challenge_start', 'challenges', ['start_date'], unique=False, postgresql_ops={'start_date': 'DESC'})
    op.alter_column('connected_accounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_content_engagement'), table_name='content_history')
    op.create_index('idx_content_engagement', 'content_history', ['engagement_rate'], unique=False, postgresql_ops={'engagement_rate': 'DESC'})
    op.drop_index(op.f('idx_content_published'), table_name='content_history')
    op.create_index('idx_content_published', 'content_history', ['published_at'], unique=False, postgresql_ops={'published_at': 'DESC'})
    op.alter_column('content_library_items', 'hashtags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_library_items', 'mentions',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_library_items', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_library_items', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_library_created'), table_name='content_library_items')
    op.create_index('idx_library_created', 'content_library_items', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_follower_date'), table_name='follower_stats')
    op.create_index('idx_follower_date', 'follower_stats', ['recorded_date'], unique=False, postgresql_ops={'recorded_date': 'DESC'})
    op.drop_index(op.f('idx_generated_created'), table_name='generated_content')
    op.create_index('idx_generated_created', 'generated_content', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_hook_performance'), table_name='hook_list')
    op.create_index('idx_hook_performance', 'hook_list', ['avg_performance'], unique=False, postgresql_ops={'avg_performance': 'DESC'})
    op.drop_index(op.f('idx_hook_times_used'), table_name='hook_list')
    op.create_index('idx_hook_times_used', 'hook_list', ['times_used'], unique=False, postgresql_ops={'times_used': 'DESC'})
    op.alter_column('media_attachments', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('post_analytics', 'views',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('post_analytics', 'likes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('post_analytics', 'comments',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('post_analytics', 'shares',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('post_analytics', 'saves',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('post_analytics', 'clicks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('post_analytics', 'impressions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('post_analytics', 'reach',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('post_analytics', 'engagement_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_analytics_engagement'), table_name='post_analytics')
    op.create_index('idx_analytics_engagement', 'post_analytics', ['engagement_rate'], unique=False, postgresql_ops={'engagement_rate': 'DESC'})
    op.drop_index(op.f('idx_analytics_synced'), table_name='post_analytics')
    op.create_index('idx_analytics_synced', 'post_analytics', ['synced_at'], unique=False, postgresql_ops={'synced_at': 'DESC'})
    op.alter_column('scheduled_posts', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scheduled_posts', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_scheduled_published'), table_name='scheduled_posts')
    op.create_index('idx_scheduled_published', 'scheduled_posts', ['published_at'], unique=False, postgresql_ops={'published_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scheduled_published', table_name='scheduled_posts', postgresql_ops={'published_at': 'DESC'})
    op.create_index(op.f('idx_scheduled_published'), 'scheduled_posts', [sa.literal_column('published_at DESC')], unique=False)
    op.alter_column('scheduled_posts', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('scheduled_posts', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'UTC'::character varying"),
               existing_nullable=False)
    op.drop_index('idx_analytics_synced', table_name='post_analytics', postgresql_ops={'synced_at': 'DESC'})
    op.create_index(op.f('idx_analytics_synced'), 'post_analytics', [sa.literal_column('synced_at DESC')], unique=False)
    op.drop_index('idx_analytics_engagement', table_name='post_analytics', postgresql_ops={'engagement_rate': 'DESC'})
    op.create_index(op.f('idx_analytics_engagement'), 'post_analytics', [sa.literal_column('engagement_rate DESC')], unique=False)
    op.alter_column('post_analytics', 'engagement_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.alter_column('post_analytics', 'reach',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('post_analytics', 'impressions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('post_analytics', 'clicks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('post_analytics', 'saves',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('post_analytics', 'shares',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('post_analytics', 'comments',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('post_analytics', 'likes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('post_analytics', 'views',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('media_attachments', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index('idx_hook_times_used', table_name='hook_list', postgresql_ops={'times_used': 'DESC'})
    op.create_index(op.f('idx_hook_times_used'), 'hook_list', [sa.literal_column('times_used DESC')], unique=False)
    op.drop_index('idx_hook_performance', table_name='hook_list', postgresql_ops={'avg_performance': 'DESC'})
    op.create_index(op.f('idx_hook_performance'), 'hook_list', [sa.literal_column('avg_performance DESC')], unique=False)
    op.drop_index('idx_generated_created', table_name='generated_content', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_generated_created'), 'generated_content', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_follower_date', table_name='follower_stats', postgresql_ops={'recorded_date': 'DESC'})
    op.create_index(op.f('idx_follower_date'), 'follower_stats', [sa.literal_column('recorded_date DESC')], unique=False)
    op.drop_index('idx_library_created', table_name='content_library_items', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_library_created'), 'content_library_items', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('content_library_items', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('content_library_items', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.alter_column('content_library_items', 'mentions',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.alter_column('content_library_items', 'hashtags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.drop_index('idx_content_published', table_name='content_history', postgresql_ops={'published_at': 'DESC'})
    op.create_index(op.f('idx_content_published'), 'content_history', [sa.literal_column('published_at DESC')], unique=False)
    op.drop_index('idx_content_engagement', table_name='content_history', postgresql_ops={'engagement_rate': 'DESC'})
    op.create_index(op.f('idx_content_engagement'), 'content_history', [sa.literal_column('engagement_rate DESC')], unique=False)
    op.alter_column('connected_accounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index('idx_challenge_start', table_name='challenges', postgresql_ops={'start_date': 'DESC'})
    op.create_index(op.f('idx_challenge_start'), 'challenges', [sa.literal_column('start_date DESC')], unique=False)
    op.drop_index('idx_job_app_user', table_name='job_applications')
    op.drop_index('idx_job_app_status', table_name='job_applications')
    op.drop_index('idx_job_app_outcome', table_name='job_applications')
    op.drop_index('idx_job_app_date_applied', table_name='job_applications')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
