apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: carteros

resources:
  - secrets.yaml
  - configmap.yaml
  - postgres-statefulset.yaml
  - redis-statefulset.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
