"""content

Revision ID: 9a0f191ed4f7
Revises: 0ab6220c405b
Create Date: 2025-12-14 03:59:53.123106
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9a0f191ed4f7'
down_revision: Union[str, None] = '0ab6220c405b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_history',
    sa.Column('platform', sa.Enum('tiktok', 'youtube', 'instagram', 'reddit', 'linkedin', 'twitter', name='platformtype'), nullable=False),
    sa.Column('content_type', sa.Enum('video', 'post', 'thread', 'short', name='contenttype'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('script_or_content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'published', 'deleted', name='contentstatus'), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('what_worked', sa.Text(), nullable=True),
    sa.Column('what_didnt', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_history'))
    )
    op.create_index('idx_content_engagement', 'content_history', ['engagement_rate'], unique=False, postgresql_ops={'engagement_rate': 'DESC'})
    op.create_index('idx_content_platform', 'content_history', ['platform'], unique=False)
    op.create_index('idx_content_published', 'content_history', ['published_at'], unique=False, postgresql_ops={'published_at': 'DESC'})
    op.create_index('idx_content_status', 'content_history', ['status'], unique=False)
    op.create_index('idx_content_tags', 'content_history', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_content_topic', 'content_history', ['topic'], unique=False)
    op.create_table('content_repurposing',
    sa.Column('source_platform', sa.String(length=50), nullable=False),
    sa.Column('target_platform', sa.String(length=50), nullable=False),
    sa.Column('adaptation_strategy', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_repurposing'))
    )
    op.create_table('cross_platform_rules',
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('applies_to', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cross_platform_rules')),
    sa.UniqueConstraint('rule', name=op.f('uq_cross_platform_rules_rule'))
    )
    op.create_table('hashtag_strategy',
    sa.Column('max_count', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hashtag_strategy')),
    sa.UniqueConstraint('position', name=op.f('uq_hashtag_strategy_position'))
    )
    op.create_table('linkedin_formatting',
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_linkedin_formatting')),
    sa.UniqueConstraint('rule_name', name=op.f('uq_linkedin_formatting_rule_name'))
    )
    op.create_table('linkedin_hooks',
    sa.Column('hook_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('best_for', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_linkedin_hooks'))
    )
    op.create_table('linkedin_post_formats',
    sa.Column('format_name', sa.String(length=100), nullable=False),
    sa.Column('engagement_multiplier', sa.String(length=50), nullable=True),
    sa.Column('optimal_specs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_linkedin_post_formats')),
    sa.UniqueConstraint('format_name', name=op.f('uq_linkedin_post_formats_format_name'))
    )
    op.create_table('linkedin_rules',
    sa.Column('page_type', sa.Enum('personal', 'company', name='linkedinpagetype'), nullable=False),
    sa.Column('content_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('character_limit', sa.Integer(), nullable=True),
    sa.Column('first_visible_chars', sa.Integer(), nullable=True),
    sa.Column('emoji_usage', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_linkedin_rules')),
    sa.UniqueConstraint('page_type', name=op.f('uq_linkedin_rules_page_type'))
    )
    op.create_table('platform_rules',
    sa.Column('platform', sa.Enum('tiktok', 'youtube', 'instagram', 'reddit', 'linkedin', 'twitter', name='platformtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_rules')),
    sa.UniqueConstraint('platform', name=op.f('uq_platform_rules_platform'))
    )
    op.create_table('reddit_engagement_tactics',
    sa.Column('tactic', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reddit_engagement_tactics'))
    )
    op.create_table('reddit_forbidden_patterns',
    sa.Column('pattern_type', sa.Enum('em_dash', 'hyphen', 'ai_language', name='forbiddenpatterntype'), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.Enum('warning', 'error', 'critical', name='patternseverity'), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('example_wrong', sa.Text(), nullable=True),
    sa.Column('example_right', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reddit_forbidden_patterns'))
    )
    op.create_index('idx_forbidden_severity', 'reddit_forbidden_patterns', ['severity'], unique=False)
    op.create_table('reddit_formatting',
    sa.Column('rule_category', sa.String(length=100), nullable=False),
    sa.Column('rule_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reddit_formatting')),
    sa.UniqueConstraint('rule_category', name=op.f('uq_reddit_formatting_rule_category'))
    )
    op.create_table('reddit_post_types',
    sa.Column('post_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('what_works', sa.Text(), nullable=True),
    sa.Column('example_good', sa.Text(), nullable=True),
    sa.Column('example_bad', sa.Text(), nullable=True),
    sa.Column('performance', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reddit_post_types')),
    sa.UniqueConstraint('post_type', name=op.f('uq_reddit_post_types_post_type'))
    )
    op.create_table('reddit_subreddits',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('self_promotion_allowed', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'highest', name='subredditpriority'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reddit_subreddits')),
    sa.UniqueConstraint('name', name=op.f('uq_reddit_subreddits_name'))
    )
    op.create_index('idx_subreddits_priority', 'reddit_subreddits', ['priority'], unique=False)
    op.create_index('idx_subreddits_self_promo', 'reddit_subreddits', ['self_promotion_allowed'], unique=False)
    op.create_table('reddit_timing',
    sa.Column('time_window', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('day_of_week', sa.String(length=50), nullable=True),
    sa.Column('performance_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reddit_timing'))
    )
    op.create_table('reddit_upvote_drivers',
    sa.Column('criterion', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reddit_upvote_drivers')),
    sa.UniqueConstraint('criterion', name=op.f('uq_reddit_upvote_drivers_criterion'))
    )
    op.create_table('tiktok_common_mistakes',
    sa.Column('mistake_type', sa.Enum('retention_killer', 'algorithm_error', name='tiktokmistaketype'), nullable=False),
    sa.Column('mistake', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('performance_impact', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiktok_common_mistakes'))
    )
    op.create_table('tiktok_cta_strategies',
    sa.Column('video_length', sa.String(length=50), nullable=False),
    sa.Column('placement', sa.Text(), nullable=False),
    sa.Column('high_converting_examples', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiktok_cta_strategies'))
    )
    op.create_table('tiktok_hook_formulas',
    sa.Column('formula_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('examples', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiktok_hook_formulas'))
    )
    op.create_table('tiktok_hook_system',
    sa.Column('hook_type', sa.Enum('visual', 'text', 'verbal', name='tiktokhooktype'), nullable=False),
    sa.Column('timing', sa.String(length=100), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('max_words', sa.Integer(), nullable=True),
    sa.Column('examples', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('performance_stat', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiktok_hook_system'))
    )
    op.create_table('tiktok_pacing',
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('rule_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiktok_pacing')),
    sa.UniqueConstraint('rule_type', name=op.f('uq_tiktok_pacing_rule_type'))
    )
    op.create_table('tiktok_platform_specifics',
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiktok_platform_specifics')),
    sa.UniqueConstraint('metric_name', name=op.f('uq_tiktok_platform_specifics_metric_name'))
    )
    op.create_table('tiktok_retention_tactics',
    sa.Column('tactic_category', sa.String(length=100), nullable=False),
    sa.Column('tactic_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiktok_retention_tactics'))
    )
    op.create_table('tiktok_rules',
    sa.Column('rule_category', sa.Enum('video_length', 'visual_style', 'hooks', 'sentence_structure', 'cta', name='tiktokrulecategory'), nullable=False),
    sa.Column('rule_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiktok_rules')),
    sa.UniqueConstraint('rule_category', name=op.f('uq_tiktok_rules_rule_category'))
    )
    op.create_table('tiktok_structure_templates',
    sa.Column('video_length', sa.String(length=50), nullable=False),
    sa.Column('timestamp_range', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('energy_level', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiktok_structure_templates'))
    )
    op.create_table('twitter_engagement_tactics',
    sa.Column('tactic_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('implementation', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_twitter_engagement_tactics')),
    sa.UniqueConstraint('tactic_name', name=op.f('uq_twitter_engagement_tactics_tactic_name'))
    )
    op.create_table('twitter_format_strategy',
    sa.Column('format_type', sa.String(length=100), nullable=False),
    sa.Column('format_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_twitter_format_strategy')),
    sa.UniqueConstraint('format_type', name=op.f('uq_twitter_format_strategy_format_type'))
    )
    op.create_table('twitter_hooks',
    sa.Column('hook_formula', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('psychological_trigger', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_twitter_hooks'))
    )
    op.create_table('twitter_rules',
    sa.Column('strategy', sa.Text(), nullable=False),
    sa.Column('tweet_length_target', sa.String(length=100), nullable=True),
    sa.Column('what_hits', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('growth_pattern', sa.Text(), nullable=True),
    sa.Column('topics_approach', sa.Text(), nullable=True),
    sa.Column('tone', sa.Text(), nullable=True),
    sa.Column('use_hashtags', sa.Boolean(), nullable=False),
    sa.Column('difficulty_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_twitter_rules'))
    )
    op.create_table('twitter_thread_architecture',
    sa.Column('framework_name', sa.String(length=100), nullable=False),
    sa.Column('structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_twitter_thread_architecture')),
    sa.UniqueConstraint('framework_name', name=op.f('uq_twitter_thread_architecture_framework_name'))
    )
    op.create_table('twitter_viral_patterns',
    sa.Column('pattern_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('examples', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_twitter_viral_patterns')),
    sa.UniqueConstraint('pattern_name', name=op.f('uq_twitter_viral_patterns_pattern_name'))
    )
    op.create_table('youtube_hook_types',
    sa.Column('hook_type', sa.String(length=100), nullable=False),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('best_for', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_hook_types'))
    )
    op.create_table('youtube_pacing',
    sa.Column('video_type', sa.String(length=100), nullable=False),
    sa.Column('optimal_length', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_pacing'))
    )
    op.create_table('youtube_rules',
    sa.Column('video_length_philosophy', sa.Text(), nullable=True),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('script_structure_approach', sa.Text(), nullable=True),
    sa.Column('seo_importance', sa.Text(), nullable=True),
    sa.Column('thumbnail_importance', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_rules'))
    )
    op.create_table('youtube_seo',
    sa.Column('seo_category', sa.String(length=100), nullable=False),
    sa.Column('seo_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_seo')),
    sa.UniqueConstraint('seo_category', name=op.f('uq_youtube_seo_seo_category'))
    )
    op.create_table('youtube_structure_frameworks',
    sa.Column('framework_name', sa.String(length=100), nullable=False),
    sa.Column('framework_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_structure_frameworks')),
    sa.UniqueConstraint('framework_name', name=op.f('uq_youtube_structure_frameworks_framework_name'))
    )
    op.create_table('youtube_viral_patterns',
    sa.Column('pattern_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('examples', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_viral_patterns')),
    sa.UniqueConstraint('pattern_name', name=op.f('uq_youtube_viral_patterns_pattern_name'))
    )
    op.create_table('hook_list',
    sa.Column('hook_text', sa.Text(), nullable=False),
    sa.Column('hook_category', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.Enum('tiktok', 'youtube', 'instagram', 'reddit', 'linkedin', 'twitter', name='platformtype'), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('avg_performance', sa.Float(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('example_video_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['example_video_id'], ['content_history.id'], name=op.f('fk_hook_list_example_video_id_content_history')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hook_list'))
    )
    op.create_index('idx_hook_category', 'hook_list', ['hook_category'], unique=False)
    op.create_index('idx_hook_performance', 'hook_list', ['avg_performance'], unique=False, postgresql_ops={'avg_performance': 'DESC'})
    op.create_index('idx_hook_platform', 'hook_list', ['platform'], unique=False)
    op.create_index('idx_hook_times_used', 'hook_list', ['times_used'], unique=False, postgresql_ops={'times_used': 'DESC'})
    op.create_table('reddit_subreddit_rules',
    sa.Column('subreddit_id', sa.Uuid(), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subreddit_id'], ['reddit_subreddits.id'], name=op.f('fk_reddit_subreddit_rules_subreddit_id_reddit_subreddits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reddit_subreddit_rules'))
    )
    op.create_table('workflow_sessions',
    sa.Column('platform', sa.Enum('tiktok', 'youtube', 'instagram', 'reddit', 'linkedin', 'twitter', name='platformtype'), nullable=False),
    sa.Column('mode', sa.Enum('give_me_ideas', 'i_have_idea', name='workflowmode'), nullable=False),
    sa.Column('current_stage', sa.Enum('ideas', 'hooks', 'hook_analysis', 'titles', 'title_analysis', 'script', 'script_analysis', 'structure', 'structure_analysis', 'body', 'body_analysis', 'content', 'content_analysis', 'final_review', name='workflowstage'), nullable=False),
    sa.Column('initial_idea', sa.Text(), nullable=True),
    sa.Column('final_content_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['final_content_id'], ['content_history.id'], name=op.f('fk_workflow_sessions_final_content_id_content_history')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_sessions'))
    )
    op.create_index('idx_sessions_platform', 'workflow_sessions', ['platform'], unique=False)
    op.create_index('idx_sessions_stage', 'workflow_sessions', ['current_stage'], unique=False)
    op.create_table('generated_content',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('tiktok', 'youtube', 'instagram', 'reddit', 'linkedin', 'twitter', name='platformtype'), nullable=False),
    sa.Column('workflow_stage', sa.Enum('ideas', 'hooks', 'hook_analysis', 'titles', 'title_analysis', 'script', 'script_analysis', 'structure', 'structure_analysis', 'body', 'body_analysis', 'content', 'content_analysis', 'final_review', name='workflowstage'), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_selected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('generated', 'user_modified', 'approved', 'published', 'archived', name='generatedcontentstatus'), nullable=False),
    sa.Column('published_content_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['generated_content.id'], name=op.f('fk_generated_content_parent_id_generated_content'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_content_id'], ['content_history.id'], name=op.f('fk_generated_content_published_content_id_content_history')),
    sa.ForeignKeyConstraint(['session_id'], ['workflow_sessions.id'], name=op.f('fk_generated_content_session_id_workflow_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_content'))
    )
    op.create_index('idx_generated_created', 'generated_content', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_generated_parent', 'generated_content', ['parent_id'], unique=False)
    op.create_index('idx_generated_platform', 'generated_content', ['platform'], unique=False)
    op.create_index('idx_generated_session', 'generated_content', ['session_id'], unique=False)
    op.create_index('idx_generated_stage', 'generated_content', ['workflow_stage'], unique=False)
    op.create_index('idx_generated_status', 'generated_content', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_generated_status', table_name='generated_content')
    op.drop_index('idx_generated_stage', table_name='generated_content')
    op.drop_index('idx_generated_session', table_name='generated_content')
    op.drop_index('idx_generated_platform', table_name='generated_content')
    op.drop_index('idx_generated_parent', table_name='generated_content')
    op.drop_index('idx_generated_created', table_name='generated_content', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('generated_content')
    op.drop_index('idx_sessions_stage', table_name='workflow_sessions')
    op.drop_index('idx_sessions_platform', table_name='workflow_sessions')
    op.drop_table('workflow_sessions')
    op.drop_table('reddit_subreddit_rules')
    op.drop_index('idx_hook_times_used', table_name='hook_list', postgresql_ops={'times_used': 'DESC'})
    op.drop_index('idx_hook_platform', table_name='hook_list')
    op.drop_index('idx_hook_performance', table_name='hook_list', postgresql_ops={'avg_performance': 'DESC'})
    op.drop_index('idx_hook_category', table_name='hook_list')
    op.drop_table('hook_list')
    op.drop_table('youtube_viral_patterns')
    op.drop_table('youtube_structure_frameworks')
    op.drop_table('youtube_seo')
    op.drop_table('youtube_rules')
    op.drop_table('youtube_pacing')
    op.drop_table('youtube_hook_types')
    op.drop_table('twitter_viral_patterns')
    op.drop_table('twitter_thread_architecture')
    op.drop_table('twitter_rules')
    op.drop_table('twitter_hooks')
    op.drop_table('twitter_format_strategy')
    op.drop_table('twitter_engagement_tactics')
    op.drop_table('tiktok_structure_templates')
    op.drop_table('tiktok_rules')
    op.drop_table('tiktok_retention_tactics')
    op.drop_table('tiktok_platform_specifics')
    op.drop_table('tiktok_pacing')
    op.drop_table('tiktok_hook_system')
    op.drop_table('tiktok_hook_formulas')
    op.drop_table('tiktok_cta_strategies')
    op.drop_table('tiktok_common_mistakes')
    op.drop_table('reddit_upvote_drivers')
    op.drop_table('reddit_timing')
    op.drop_index('idx_subreddits_self_promo', table_name='reddit_subreddits')
    op.drop_index('idx_subreddits_priority', table_name='reddit_subreddits')
    op.drop_table('reddit_subreddits')
    op.drop_table('reddit_post_types')
    op.drop_table('reddit_formatting')
    op.drop_index('idx_forbidden_severity', table_name='reddit_forbidden_patterns')
    op.drop_table('reddit_forbidden_patterns')
    op.drop_table('reddit_engagement_tactics')
    op.drop_table('platform_rules')
    op.drop_table('linkedin_rules')
    op.drop_table('linkedin_post_formats')
    op.drop_table('linkedin_hooks')
    op.drop_table('linkedin_formatting')
    op.drop_table('hashtag_strategy')
    op.drop_table('cross_platform_rules')
    op.drop_table('content_repurposing')
    op.drop_index('idx_content_topic', table_name='content_history')
    op.drop_index('idx_content_tags', table_name='content_history', postgresql_using='gin')
    op.drop_index('idx_content_status', table_name='content_history')
    op.drop_index('idx_content_published', table_name='content_history', postgresql_ops={'published_at': 'DESC'})
    op.drop_index('idx_content_platform', table_name='content_history')
    op.drop_index('idx_content_engagement', table_name='content_history', postgresql_ops={'engagement_rate': 'DESC'})
    op.drop_table('content_history')
    # ### end Alembic commands ###
